---

- name: Change primary for replication 
  community.mysql.mysql_replication:
    mode: changeprimary
    primary_user: repl
    primary_password: "password"
    primary_host: 192.168.15.200
    primary_log_file: mysql-bin.000001
    primary_ssl: 1
    primary_log_pos: 157

- name: Reloading mysql
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Reseting replication
  community.mysql.mysql_replication:
    mode: resetreplica
  
- name: start replication
  community.mysql.mysql_replication:
    mode: startreplica
