---
- name: Installation node_exporter
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
    - node_exporter

- name: Install monitoring system
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
    - prometheus
    - alertmanager
    - grafana
